// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmhhfC5Ir3cGWX-OAxq9k4aKEuUINr5W4',
    appId: '1:627672977436:web:4574a832c2a38b20c7cfd9',
    messagingSenderId: '627672977436',
    projectId: 'photoshare-61612',
    authDomain: 'photoshare-61612.firebaseapp.com',
    storageBucket: 'photoshare-61612.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBad6xU-vsPaekAjKK_KADAoqvQNErg3B4',
    appId: '1:627672977436:android:67e8c96407a9863ec7cfd9',
    messagingSenderId: '627672977436',
    projectId: 'photoshare-61612',
    storageBucket: 'photoshare-61612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPFw8D4W17oYpdEvO0gaPHAhChWOWV_a8',
    appId: '1:627672977436:ios:2c95d4424cff4c21c7cfd9',
    messagingSenderId: '627672977436',
    projectId: 'photoshare-61612',
    storageBucket: 'photoshare-61612.firebasestorage.app',
    iosBundleId: 'com.example.photoSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPFw8D4W17oYpdEvO0gaPHAhChWOWV_a8',
    appId: '1:627672977436:ios:2c95d4424cff4c21c7cfd9',
    messagingSenderId: '627672977436',
    projectId: 'photoshare-61612',
    storageBucket: 'photoshare-61612.firebasestorage.app',
    iosBundleId: 'com.example.photoSharing',
  );
}
