// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbuVw6au1BRwOtA5GF1yWQ1vXgWpIW4k',
    appId: '1:857815304247:web:c6b58cf63c3904c07a57b2',
    messagingSenderId: '857815304247',
    projectId: 'restaurant-183c3',
    authDomain: 'restaurant-183c3.firebaseapp.com',
    storageBucket: 'restaurant-183c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpfmR3io9C5KDLRGoa9hsGCaDVIRBwaU',
    appId: '1:857815304247:android:2c6ef411875399c67a57b2',
    messagingSenderId: '857815304247',
    projectId: 'restaurant-183c3',
    storageBucket: 'restaurant-183c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiu_w9OwqfTZFuBeqOwyzoyxxBJXRh4G8',
    appId: '1:857815304247:ios:e6fd704c769a434b7a57b2',
    messagingSenderId: '857815304247',
    projectId: 'restaurant-183c3',
    storageBucket: 'restaurant-183c3.firebasestorage.app',
    iosBundleId: 'com.example.restaurantUpgrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiu_w9OwqfTZFuBeqOwyzoyxxBJXRh4G8',
    appId: '1:857815304247:ios:e6fd704c769a434b7a57b2',
    messagingSenderId: '857815304247',
    projectId: 'restaurant-183c3',
    storageBucket: 'restaurant-183c3.firebasestorage.app',
    iosBundleId: 'com.example.restaurantUpgrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:your-project-number:web:your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}