// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6j54ytRQsv1pwVCMZYLxe6T8SfBDKTyw',
    appId: '1:502247829936:web:56da668c0877932bfee675',
    messagingSenderId: '502247829936',
    projectId: 'expense-7c9ac',
    authDomain: 'expense-7c9ac.firebaseapp.com',
    storageBucket: 'expense-7c9ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADgWW9viLBN6SlV7ZSj51lp-G4ThnvuQ',
    appId: '1:502247829936:android:b7a84150e48f2947fee675',
    messagingSenderId: '502247829936',
    projectId: 'expense-7c9ac',
    storageBucket: 'expense-7c9ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZwbsx-fSMuY6uyznPntTb7IGXxfN3qZw',
    appId: '1:502247829936:ios:c348280b38919646fee675',
    messagingSenderId: '502247829936',
    projectId: 'expense-7c9ac',
    storageBucket: 'expense-7c9ac.firebasestorage.app',
    iosBundleId: 'com.example.expenseUpgrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZwbsx-fSMuY6uyznPntTb7IGXxfN3qZw',
    appId: '1:502247829936:ios:c348280b38919646fee675',
    messagingSenderId: '502247829936',
    projectId: 'expense-7c9ac',
    storageBucket: 'expense-7c9ac.firebasestorage.app',
    iosBundleId: 'com.example.expenseUpgrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}