type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Category @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  description: String
  isPublic: Boolean
}

type Item @table {
  user: User!
  category: Category
  name: String!
  createdAt: Timestamp!
  description: String
  isPublic: Boolean
}

type AttributeDefinition @table {
  user: User!
  name: String!
  type: String! # e.g., "TEXT", "NUMBER", "DATE", "BOOLEAN"
  createdAt: Timestamp!
}

type AttributeValue @table {
  item: Item!
  attributeDefinition: AttributeDefinition!
  value: String! # Storing as String for flexibility to represent different types (e.g., "true", "123", "2023-01-01")
  createdAt: Timestamp!
}