// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-xoKyz8HziliZB2W-Ujqf53VdglK24h8',
    appId: '1:1004343494151:web:bb95a7fecd4c88aa970ca2',
    messagingSenderId: '1004343494151',
    projectId: 'cookbookcollection-ee091',
    authDomain: 'cookbookcollection-ee091.firebaseapp.com',
    storageBucket: 'cookbookcollection-ee091.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgDHHAByacJKMyKoqxGznrQxkZfeDJsk',
    appId: '1:1004343494151:android:7aec5a7ec6cef124970ca2',
    messagingSenderId: '1004343494151',
    projectId: 'cookbookcollection-ee091',
    storageBucket: 'cookbookcollection-ee091.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lLhH7Oi5zq8O-Qa4ROYtupVI3HE51jI',
    appId: '1:1004343494151:ios:7005ac1c6181a51d970ca2',
    messagingSenderId: '1004343494151',
    projectId: 'cookbookcollection-ee091',
    storageBucket: 'cookbookcollection-ee091.firebasestorage.app',
    iosBundleId: 'com.example.cookbookCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lLhH7Oi5zq8O-Qa4ROYtupVI3HE51jI',
    appId: '1:1004343494151:ios:7005ac1c6181a51d970ca2',
    messagingSenderId: '1004343494151',
    projectId: 'cookbookcollection-ee091',
    storageBucket: 'cookbookcollection-ee091.firebasestorage.app',
    iosBundleId: 'com.example.cookbookCollection',
  );
}
